version: 1

modules:
  strategies:
    dir: 'strategies'  
    strat1:
      dir: 'strat1'
    strat2:
      dir: 'strat2'
  brokers:
    dir: 'brokers'
    alpaca:
      git: 'github.com/TheCyberHead/alpaca'
